Server/Core/Server.cs
Added null check for keepalive timer callback to prevent server
application from crashing when stopping the listen server when client(s)
connect and initiate the keepalive timer
=> Bugfix with listen server

Client/Core/ProtoBuf/Meta/ValueMember.cs, Server/Core/ProtoBuf/Meta/ValueMember.cs, Server/Forms/FrmRemoteDesktop.cs
Fixed an issue where Remote Desktop would not work (threw infinite
InvalidOperationExceptions) because cbMonitors.SelectedIndex was trying
to be accessed on a different thread.
Moved code that gets the SelectedIndex inside the MethodInvoker.
=> Fixed issue with the Remote Desktop

Client/Core/Encryption/SHA256.cs
String concatenation in loops are not optimized and are incredibly slow because strings are immutable. Implemented a StringBuilder to build the hash instead of concatenating a string to make it exponentially faster.
=> Encryption speed increase

Client/Core/Client.cs
Fixed a bug where after using Remote Desktop and client
disconnection/reconnection, the server wasn't able to run Remote Desktop
again.  I believe there is an issue with the buffer/flow in the
UnsafeStreamCodec class however I wasn't able to pinpoint it.  Setting
this object to null allows a new object to be created when running
Remote Desktop with a fresh buffer.
=> Bugfix with Remote Desktop

Server/Core/Commands/CommandHandler.cs
added try catch blocks due to server application crashing while closing
the remote desktop form.  If timed right, while closing the remote
desktop form, the command handler would be in the midst of accessing an
already disposed form causing server to hang.
=> Bugfix #2 with Remote Desktop

Client/Core/Compression/SafeQuickLZ.cs, Client/Core/Helper/FileSplit.cs, Server/Core/Compression/SafeQuickLZ.cs, Server/Core/Helper/FileSplit.cs, Server/Core/Helper/UPnP.cs, Server/Core/Server.cs, Server/Forms/FrmBuilder.cs
Fixed a rather small memory leak with the Server Socket potentially not being disposed of correctly, fixed a loop in the Server's 'UPnP' class that only gave one chance for a valid end-point to be found, improved the consistency in some parts of the code, optimized both of the 'SafeQuickLZ' class's Compression method, and compacted the Builder Form's 'Build' method to improve speed and to reduce redundancy .
=> Code Consistency and Clarity, Performance, and a Small Fix

Client/Core/Commands/CommandHandler.cs, Server/Core/Commands/CommandHandler.cs
Removed unnecessary null check (duplicate null check, was already checked in the method!), and removed an unnecessary Stream that was created when the Client is commanded to visit a URL. We already got the response, so we don't need to do anything further!
Also fixed a CrossThreadException that would be caused by HandleGetSystemInfoResponse if called by a different Thread.
=> Unnecessary code removal and Cross-Thread issue fix

Server/Forms/FrmFileManager.cs, Server/Forms/FrmSettings.cs, Server/Forms/FrmTermsOfUse.cs
1) Terms of Use Form closes in a different way.
... By killing a process using Process.Kill(), the process is terminated forcefully and does not allow finally-blocks or finalizers to be executed. This is not a desirable effect and can potentially cause difficult-to-find bugs. Should use Application.Exit() in its place.
2) Rewrote a method and improved another
... The Listen method now uses try-finally blocks so that the state of the Settings Form doesn't get stuck if a Socket Exception occurs.
... Rewrote a method in the File Manager Form that performs the same decisions, but is much simpler, requires less strings to be created, and doesn't need to make the same decision twice without reason.
=> Some improved behavior changes

Client/Core/Keylogger/Logger.cs
removed f1-f11 keys since they are not handled
moved calling the keyboard layout to FromKeys method when a key is
handled so its not being called every 10ms
=> Keylogger cleanup

Client/Core/Keylogger/Logger.cs, Client/Program.cs
1) Fixed two typos.
2) Fixed an issue that caused incorrect logging of certain special key combinations.
3) Fixed incorrect documentation in the Keylogger.
4) Made the flush interval smaller for the client and added a bit of documentation to the Logger's constructor.
=> Fixes and improvements to the keylogger

Server/Forms/FrmReverseProxy.cs
Closing this form without doing anything causes a crash because RefreshTimer hasn't been initialized yet
=> Fixed null reference crash

Client/Core/Keylogger/KeyloggerHelpers.cs, Client/Core/Keylogger/KeyloggerKeys.cs, Client/Core/Keylogger/Logger.cs, Client/Core/Keylogger/Win32.cs, Client/Program.cs, Server/Core/Build/Renamer.cs
Bugs: Thread doesn't exit when disabling the hook, has something to do with message pump I believe
Todo: handle modifier keys in another manner.  for example a user presses control, and while control is down the user decides to press a, the log will display [CTRL][CTRL + a]
=> Keylogger hook

Client/Core/RemoteShell/Shell.cs
Should fix second issue of https://github.com/MaxXor/xRAT/issues/153
<hr />
<h2>Brief Explanation</h2>
<code>Process.Kill()</code> can throw quite a few different exceptions. While checking if the process has exited makes it slightly safer, exceptions can still be thrown for many other reasons (perhaps the process is already terminating, or a process can not be terminated).
The point of it should be: Make sure the process is not null. If it has not exited yet, try to kill it. If it can't be killed, do not worry anymore and simply dispose of it because it.
=> Fixes for uninstall issues

Server/Core/Build/Renamer.cs
Ignore renaming types that implement interfaces.
I hope this is the correct way to do this, I couldn't find a way to find
a specific interface to exclude from obfuscation
=> IDisposable TypeloadException fix

Server/Forms/FrmKeylogger.cs
<h1>Reproduction of the issue</h1>
- Open up a keylogger form and make sure no entries are selected.
- Invoke the <b><a href="https://github.com/MaxXor/xRAT/blob/master/Server/Forms/FrmKeylogger.cs#L56">lstLogs_ItemActivate</a></b> method by pressing enter.
- Since no items are selected, it cannot index the 0th item of lstLogs' SelectedItems, causing an exception that is uncaught and crashes the server.
=> Fixed server crash on FrmKeylogger

Client/Core/Client.cs, Client/Core/Helper/FileSplit.cs, Client/Core/Helper/Helper.cs, Server/Core/Client.cs, Server/Core/Helper/FileSplit.cs, Server/Core/Helper/Helper.cs
<h1>Exceptions</h1>
- Exceptions provide better responses for the server (providing more-accurate status updates). It also makes debugging a bit easier
- Add types to serializer faster. When a matching subtype's derived type is found, break out of the loop.
<h1>Performance</h1>
- <b>Big</b> reduction on memory consumption when using Remote Desktop (for Client).
- Faster retrieval of file size.
=> Improvements

Client/Core/Keylogger/Logger.cs, Client/Program.cs
Fixed the message loop, called Application.Run in the thread and not the logger
object, using ApplicationContext object we can identify the message loop to have it return, so the thread can exit gracefully
=> Message loop fix

Client/Core/Keylogger/Implementation/KeyboardState.cs, Client/Core/Keylogger/KeyPressEventArgsExt.cs, Client/Core/Keylogger/Logger.cs, Client/Core/Keylogger/LoggerHelper.cs, Client/Core/Keylogger/WinApi/KeyboardNativeMethods.cs
-Fixed spaces showing up in weird orders.
-Fixed issue where pressing some modifier keys would append the KeyPress
events text prior to the Appended highlighted text from the KeyDown
event.  Example:  User presses Windows Key + R.  it would log "r[Win +
[R]"
-POSSIBLY fixed dead keys, needs to be tested!
=> Keylogger fixes

Client/Core/Keylogger/WinApi/KeyboardNativeMethods.cs
Fixed case of pressing dead-key to accent characters followed by Shift +
character to present an uppercase character
=> dead-key fix

Client/Core/Keylogger/Logger.cs
added modifierkey check so we only ignore special key cases if modifier keys were down.  without this, pressing special keys such as dead keys followed by enter, would trigger the second if statement and would ignore displaying [Enter] and sometimes even possibly spaces
after adding this check, everything works accurately
=> Keylogger special key fix

Client/Client.csproj, Client/Core/Commands/SystemHandler.cs, Client/Core/Extensions/RegistryKeyExtensions.cs, Server/Core/Commands/SystemHandler.cs
Fixes <b><a href="https://github.com/MaxXor/xRAT/issues/256">Issue 256</a></b>.
I have no time to post a better description, so I apologize. I need to clean the method that removes registry key items later. :)
=> Startup items fix

Server/Core/Commands/MiscHandler.cs, Server/Core/Commands/SurveillanceHandler.cs, Server/Core/Commands/SystemHandler.cs
<h1>Reason</h1>
A client should <b>never</b> have the ability to break the server (cause an uncaught exception) by sending packets with invalid or otherwise unusable data.
<h1>Changes</h1>
- Added more restrictive validation to ensure usable information by the received packets on the handlers before use. This makes sure that a client that may make a strange request with bad data without causing a server crash.
=> Better server validation

Server/Core/Packets/PacketHandler.cs
For some reason, killing the Client process on my VM while Remote Desktop was running on my host would cause the Server to crash.  A NullReferenceException was thrown @ Line 16 in PacketHandler.cs.  Not sure if this is the best fix, but the server is trying to handle a packet after client.Value is nulled and the check for a value in client.Value throws the exception
=> PacketHandler fix

Server/Forms/FrmRemoteDesktop.Designer.cs, Server/Forms/FrmRemoteDesktop.cs
The form designer changes are to the tabstop so tab key presses don't interfere with keystrokes
Added form events for keypresses to support Remote Desktop through Mono
=> Remote Desktop Mono Support

Client.Tests/Client.Tests.csproj, Client.Tests/Core/Commands/MiscHandler.Tests.cs, Client/Core/Commands/MiscHandler.cs, Server/Forms/FrmMain.cs, Server/Forms/FrmUploadAndExecute.cs
=> Added the ability to upload an execute a batch file.

Server/Core/Commands/SurveillanceHandler.cs
If a client unexpectedly disconnects from the server while rdp is running, `client.Value` can be nulled before the `SurveillanceHandler` reaches this check, causing the server to crash checking for the forms instance
=> Remote Desktop form bug fix

Client/Core/Helper/SystemHelper.cs
This should fix issue #346 regarding incorrect uptime being returned.
Directly querying the uptime and subtracting it from the current time
(in UTC) allows us to convert it into a TimeSpan from the ticks and
obtain a significantly more accurate uptime.
=> Fix for #346

Client/Core/Recovery/Browsers/Firefox.cs, Server/Core/Compression/JpgCompression.cs, Server/Forms/FrmMain.cs
-Fixed obtaining Firefox path from registry. Firefox path will only be in Wow6432Node if OS is 64-bit.
-Fixed null reference exception disposing an object in `JpgCompression`
-Fixed multiple client form disposal on client disconnect for password recovery
=> Server fixes

Server/Core/Helper/NativeMethodsHelper.cs, Server/Forms/FrmRemoteShell.cs
-Will always scroll to the very bottom of the rtb when text is changed
=> RemoteShell caret positioning fix

Client/Client.csproj, Client/Core/Commands/SystemHandler.cs, Client/Core/Networking/QuasarClient.cs, Client/Core/Packets/PacketHandler.cs, Client/Core/Packets/ServerPackets/DoAskElevate.cs, Server/Core/Networking/QuasarServer.cs, Server/Core/Packets/ServerPackets/DoAskElevate.cs, Server/Forms/FrmMain.Designer.cs, Server/Forms/FrmMain.cs, Server/Forms/FrmMain.resx, Server/Server.csproj
Essentially, tells the client to ShellExecute itself which opens up a UAC Consent window that the user can accept or decline. If accepted, the original client is stopped and the new client with Admin rights connects to the server.
This is the second C# thing I've worked on, so any tips or criticism is welcome.
This is the _first_ pull request I've ever done. I'm still learning Git, too.
=> Feature: Ask To Elevate

Client/Core/Commands/SurveillanceHandler.cs, Client/Core/Helper/NativeMethodsHelper.cs, Client/Core/Utilities/NativeMethods.cs
Fixes #471 . Tested on Win7 & Win10 (x64). No significant difference in remote desktop performance after quick testing.
=> Remote desktop can now wake a client up from an active screensaver
