Client/Core/Commands/CommandHandler.cs, Client/Core/Information/GeoIP.cs, Client/Core/SystemCore.cs, Server/Core/ProtoBuf/ProtoWriter.cs
Added a few try-finally blocks to make sure that, even if an exception is thrown, behavior remains more consistent.
Also added a few using blocks to make sure that, if the method returns or an exception is thrown, we can avoid a memory leak. (Common in cases where dispose is called at the bottom of a try-catch block... If an exception was thrown, it wouldn't reach the dispose call).
=> Behavior Consistency and Memory Leaks

Client/Core/Commands/CommandHandler.cs, Client/Core/RemoteShell/Shell.cs, Server/Core/Commands/CommandHandler.cs, Server/Core/Helper/Helper.cs, Server/Core/Helper/UPnP.cs
Mostly non-functional changes to improve the clarity and quality of the code. Some changes to the code to make sure correct/intended behavior is enforced.
=> Code consistency, clarity, and improvements

Client/Config/Settings.cs, Server/Core/Commands/CommandHandler.cs, Server/Forms/FrmMain.cs
Fixed crash fix Control Cross Threading when a client connects
Result: Client's wouldn't show up
=> Cross Threading bugfix

Client/Client.csproj, Client/Core/Client.cs, Client/Core/Compression/SafeQuickLZ.cs, Server/Core/Client.cs, Server/Core/Compression/SafeQuickLZ.cs, Server/Server.csproj
Fixed the compression / encryption order (Compression always failed)
Made the Client more stable but theres a bug with the Keep Alive
packets, need to be checked
Replaced LZ4 with QuickLZ, more stability
=> A more stable client & Compression Fix

Client/Client.csproj, Client/Core/Commands/CommandHandler.cs, Client/Core/Helper/Helper.cs, Client/Core/Helper/UnsafeStreamCodec.cs, Client/Core/Misc/JpgCompression.cs, Client/Program.cs, Server/Core/Commands/CommandHandler.cs, Server/Core/Helper/UnsafeStreamCodec.cs, Server/Core/Misc/JpgCompression.cs, Server/Core/UserState.cs, Server/Server.csproj
Probably fixed Remote Desktop Memory Leak, needs more testing but
overall stays between 50-100MB
Added UnsafeStreamCodec
=> Probably fixed Remote Desktop Memory Leak

Server/Core/Server.cs, Server/Core/UserState.cs
Added disposal method to dispose of all userstate forms for client upon
disconnection of the client from the server
=> Form disposal on client disconnection

Client/Client.csproj, Client/Config/Settings.cs, Client/Core/Client.cs, Client/Core/Misc/KeepAlive.cs, Server/Core/Client.cs, Server/Core/Commands/CommandHandler.cs, Server/Core/Misc/KeepAlive.cs, Server/Core/Server.cs, Server/Server.csproj
KeepAlive tested and added. Manual KeepAlive Removed. Also a handled a Cross-Thread exception when Uninstalling.
=> KeepAlive Added

Client/Core/Commands/CommandHandler.cs, Client/Core/Helper/UnsafeStreamCodec.cs, Client/Core/Packets/ClientPackets/DesktopResponse.cs, Client/Core/Packets/ServerPackets/Desktop.cs, Server/Core/Commands/CommandHandler.cs, Server/Core/Packets/ClientPackets/DesktopResponse.cs, Server/Core/Packets/ServerPackets/Desktop.cs, Server/Core/UserState.cs
- Fixed Remote Desktop crash when using multiple monitors with different
resolution
=> Fixed Remote Desktop crash

Server/Forms/FrmMain.cs
fixed mainform getting real selected item count on client disconnection
from server.
added threading to upload and execute form dialogresult ok
=> MainForm fixes

Client/Core/Keylogger/Logger.cs
Improved the code in the new Keylogger. Formatted some code to make it consistent with the rest, and optimizations.
=> Improvements to new content (Keylogger)

Client/Core/Commands/CommandHandler.cs, Server/Forms/FrmMain.cs
1) Fixed a case that would cause a client to crash if attempted to start a process that was either dysfunctional or had no file name.
2) Fixed a case that would cause the server to crash if a command was issued to upload/execute a file to a client without a valid path (could just submit an invalid path or nothing).
=> Fixed two separate crashes

Server/Core/Build/ClientBuilder.cs, Server/Core/Build/IconInjector.cs, Server/Core/Build/Renamer.cs
Because some spots can be a bit challenging to follow for those that haven't really messed with it much, I just added some documentation for the Server's Build folder.
=> Added documentation for the Server's Build folder

Client/Core/Keylogger/Logger.cs
=> null reference fix

Server/Forms/FrmMain.cs, Server/Forms/FrmSettings.Designer.cs, Server/Forms/FrmSettings.cs, Server/Settings/Settings.cs
Integrated DNS updater for NoIP.org
=> Noip integration

Client.Tests/Client.Tests.csproj, Client.Tests/Core/Compression/JpgCompressionTests.cs, Client.Tests/Core/Encryption/AES.Tests.cs, Client.Tests/Core/Information/GeoIPTests.cs, Client/Properties/AssemblyInfo.cs, Server/Properties/AssemblyInfo.cs
=> More Unit Tests

Client/Core/Elevation/FrmElevation.cs
=> Adding Arabic to supported language in elevation form

Client/Core/Commands/CommandHandler.cs, Client/Core/Packets/ClientPackets/GetProcessesResponse.cs, Server/Core/Commands/CommandHandler.cs, Server/Core/Packets/ClientPackets/GetProcessesResponse.cs, Server/Forms/FrmTaskManager.Designer.cs
=> Revert "CPU/RAM usage of each process"

Server/Core/ReverseProxy/ReverseProxyClient.cs, Server/Core/ReverseProxy/ReverseProxyServer.cs, Server/Forms/FrmReverseProxy.Designer.cs, Server/Forms/FrmReverseProxy.cs, Server/Forms/FrmReverseProxy.resx
Ability to kill connections
Improved the refreshing of the OpenConnection ListView
=> Improved Reverse Proxy UI

Client/Core/ReverseProxy/Packets/ReverseProxyConnectResponse.cs, Client/Core/ReverseProxy/ReverseProxyClient.cs, Server/Core/ReverseProxy/Packets/ReverseProxyConnectResponse.cs, Server/Core/ReverseProxy/ReverseProxyClient.cs, Server/Core/ReverseProxy/ReverseProxyServer.cs, Server/Forms/FrmMain.cs, Server/Forms/FrmReverseProxy.Designer.cs, Server/Forms/FrmReverseProxy.cs
Added a Load Balancer, this will try balancing all the proxy connections over multiple clients (keep refreshing ipchicken.com to see the cool effect)
Resolve the DNS Hostname of the Target server at the Remote Client to reduce DNS Leaks
=> Reverse Proxy Updates & Load Balancer

Server/Core/Commands/SystemHandler.cs, Server/Core/Helper/Helper.cs, Server/Forms/FrmReverseProxy.cs, Server/Forms/FrmStatistics.cs
-Changing the Func was used to calculate send/received data by reverse
proxy
*This change will view the values with decimal point (2 num) to make the
values more accurate (instead of integer values)
-Changing the func name used from "GetFileSize" to "GetDataSize" ( Found
in xServer.Core.Helper )
=> Small Change to Reverse Proxy

Client/Core/Commands/SurveillanceHandler.cs, Client/Core/Packets/ServerPackets/MouseClick.cs, Server/Core/Packets/ServerPackets/MouseClick.cs, Server/Forms/FrmRemoteDesktop.cs
Before it could only do mouse input on first monitor on a multi-monitor setup. Not sure if there'll be any issues with Y coordinates, but should be fine.
=> Add support for mouse input for multiple monitors

Client/Core/Keylogger/Logger.cs
Made a few changes, added some comments for some considerations
=> Changes to keylogger

Server/Forms/FrmBuilder.Designer.cs, Server/Forms/FrmBuilder.cs
Fixed prompt to save Profile not shown when changing the timeout.
=> Fixed bug in Builder

Client/Core/Keylogger/Logger.cs
-added escape key
-added return key to GetDisplayNames.  It wasn't displaying right for my keyboard (would display as [Return])
-added keypress list to detect multiple keypresses for characters
-moved modifier key check to a method for readability
=> Some changes to keylogger

Client/Core/Commands/SystemHandler.cs
Changed CurrentUser to LocalMachine
As these values located in LocalMachine NOT CurrentUser
=> Startup Manger Fix [Client]

Server/Core/Helper/UPnP.cs
Not sure why UPnP wasn't working, but this fixed it.  Now starting the server/stopping the server will add/remove port maps each time.
=> Server UPnP fix

Server/Core/Networking/Utilities/UPnP.cs
ref #289 
In my case, one of my devices didn't map the port until the second iteration, so we just probe the router with multiple requests to make sure that it is ready to process mapping the port.
=> UPnP ensure port map

Client/Client.csproj, Client/Core/Commands/SurveillanceHandler.cs, Client/Core/Helper/NativeMethodsHelper.cs, Client/Core/Packets/PacketHandler.cs, Client/Core/Packets/ServerPackets/DoMouseEvent.cs, Client/Enums/MouseAction.cs, Client/Enums/RemoteDesktopAction.cs, Client/Program.cs, Server/Core/Networking/ConnectionHandler.cs, Server/Core/Packets/ServerPackets/DoMouseEvent.cs, Server/Enums/MouseAction.cs, Server/Enums/RemoteDesktopAction.cs, Server/Forms/FrmRemoteDesktop.Designer.cs, Server/Forms/FrmRemoteDesktop.cs, Server/Server.csproj
Improved Mouse Inputs for the Remote Desktop function.
The mouse inputs are now real-time :)
=> Remote Desktop Mouse Input Improvements

Server/Core/Commands/MiscHandler.cs, Server/Core/Commands/SurveillanceHandler.cs, Server/Core/Commands/SystemHandler.cs
-Added some server handling checks to make sure handling of a client disconnection doesn't affect the stability of the server
=> Added Server handling checks

Client/Core/Commands/MiscHandler.cs
Fixes showing the messagebox and sending it to the front as the active window
=> DialogBox fix

Client/Core/Recovery/Browsers/Firefox.cs
LoadLibrary isn't loading the DLLs for firefox
=> #339 partial fix

Server/Forms/FrmRemoteDesktop.cs
Make sure not to handle toggle keys at application level to ensure keyboard LED responds appropriately
=> Remote desktop togglekey fix

Client/Config/Settings.cs, Client/Core/Utilities/Keylogger.cs, Server/Core/Build/ClientBuilder.cs, Server/Core/Data/BuildOptions.cs, Server/Core/Data/BuilderProfile.cs, Server/Forms/FrmBuilder.Designer.cs, Server/Forms/FrmBuilder.cs
Added option to change name of the log directory and to hide it.
=> Keylogger Enhancement

Server/Forms/FrmPasswordRecovery.cs
Added notification to display password recovery couldnt not find anything.
=> PW Recovery user notification

Server/Forms/FrmPasswordRecovery.cs
This will display better for multiple clients selected, instead of prompting messagebox for every client with no results
=> Improved PW Recovery user notification of no results + redundancy

Client/Client.csproj, Client/Core/Commands/TCPConnectionsHandler.cs, Client/Core/Networking/QuasarClient.cs, Client/Core/Packets/ClientPackets/GetConnectionsResponse.cs, Client/Core/Packets/PacketHandler.cs, Client/Core/Packets/ServerPackets/DoCloseConnection.cs, Client/Core/Packets/ServerPackets/GetConnections.cs, Server/Core/Commands/TCPConnectionsHandler.cs, Server/Core/Networking/QuasarServer.cs, Server/Core/Networking/UserState.cs, Server/Core/Packets/ClientPackets/GetConnectionsResponse.cs, Server/Core/Packets/PacketHandler.cs, Server/Core/Packets/ServerPackets/DoCloseConnection.cs, Server/Core/Packets/ServerPackets/GetConnections.cs, Server/Forms/FrmConnections.Designer.cs, Server/Forms/FrmConnections.cs, Server/Forms/FrmConnections.resx, Server/Forms/FrmMain.Designer.cs, Server/Forms/FrmMain.cs, Server/Forms/FrmMain.resx, Server/Server.csproj
+ Added the ability to get TCP connections
+ Close any connection ( If client is elevated )
[*] Icons needed
=> Added Remote TCP Connections

Client/Core/Recovery/FtpClients/FileZilla.cs
=> Fix FileZilla base64 decoding

Server/Controls/RegistryTreeView.cs, Server/Forms/FrmRegistryEditor.cs, Server/Forms/FrmRemoteWebcam.Designer.cs
-Centered webcam form on load
-Fixed flickering with nodes in registry tree view
=> Fixes to forms/controls
